
export const ERROR_CODE: { [key: string]: number } = {
  NORMAL_ERROR_CODE: 0,
  NO_PERMISSION: 1001,
  PLAYLIST_NO_PERMISSION: 1004,
  NORMAL_DATA_NOT_FOUND: 1005,
  ANALYTICS_PARAM_CHANGED: 4400,
  ANALYTICS_EXPORT_EXCEED_LIMIT: 4401,
  DASHBOARD_MY_PERFORMANCE_FIRST_TIME: 4700,
};
